### ISSUE TITLE
Part 2 Section 4 Example 2 Cyclic Iterators is duplicated at the end of Example 1.

### ISSUE THREAD

**Issue by WillieMaddox** [fbaptiste/python-deepdive#20]
The contents of `/python-deepdive/Part 2/Section 04 - Iterables and Iterators/05 - Example 2 - Cyclic Iterators.ipynb` are duplicated in the last section of 
`/python-deepdive/Part 2/Section 04 - Iterables and Iterators/04 - Example 1 - Consuming Iterators Manually.ipynb`

**Comment by fbaptiste** [comment]
Ah, yes, thank you!! I have fixed the notebook.
