### ISSUE TITLE
Order of jupyter notebooks not aligned with order of video tutorials.

### ISSUE THREAD

**Issue by WillieMaddox** [fbaptiste/python-deepdive#38]
Notebook `09 - Python's Built-In Iterables and Iterators.ipynb` in `Part 2/Section 04 - Iterables and Iterators` needs to come before notebook `07 - Sorting Iterables.ipynb`.  The video on sorting comes after the video on built-ins.

**Comment by fbaptiste** [comment]
Thanks Willie!
I have re-ordered the notebooks.
