### ISSUE TITLE
Int vs int in exponentiation.

### ISSUE THREAD

**Issue by SangamSwadiK** [fbaptiste/python-deepdive#44]
In the below notebook
https://github.com/fbaptiste/python-deepdive/blob/master/Part%201/Section%2004%20-%20Numeric%20Types/02%20-%20Integers%20-%20Operations.ipynb

It is mentioned that "int vs int in exponentiation, i.e result of 3 ** 2  always results in  an int.
However this is always not true  because of negative exponents ( 3 **-2).

**Comment by fbaptiste** [comment]
Thanks for catching that!
Fixed.
